multi/different kickstart feature for efi/bios systems

diff --git a/kickstart-usb-creator b/kickstart-usb-creator
--- a/kickstart-usb-creator
+++ b/kickstart-usb-creator
@@ -6,6 +6,8 @@ script=$(readlink -f "$0")
 script_path=$(dirname "$script")
 script_name=$(basename "$script")
 
+singleKickstart=true
+
 # shellcheck source=/dev/null
 if ! source "$script_path/_functions"; then
   echo "Function inclusion failed."
@@ -28,6 +30,38 @@ function help {
   exit 1
 }
 
+function kickstartError {
+  echo
+  echo "Error: single and multiple kickstart file options used."
+  echo "       [--ks] option allows to specify a single kickstart for EFI and BIOS systems"
+  echo "       and"
+  echo "       [--efiks] and [--biosks] options allow to specify a different kickstart for EFI and BIOS systems"
+  echo "       Using [--efiks] without [--biosks] or [--ks] with [--efiks]/[--biosks] options simultaneously is not allowed!"
+  help
+}
+
+function checkOptions {
+  # not enough kickstart file definitions
+  if [[ -z $ks ]] && ([[ -z $efiks ]] || [[ -z $biosks ]]); then
+    kickstartError
+  fi
+  if ([[ -z $efiks ]] && [[ $biosks ]]) || ([[ $efiks ]] || [[ -z $biosks ]]); then
+    kickstartError
+  fi
+  # too many kickstart file definitions
+  if ([[ $ks ]] && [[ $efiks ]]) || ([[ $ks ]] && [[ $biosks ]]); then
+    kickstartError
+  fi
+    if [[ -z "$iso" ]]; then
+    _error "Missing path to .iso file."
+    help
+  fi
+  if [[ -z "$device" ]]; then
+    _error "Missing device."
+    help
+  fi
+}
+
 
 
 # process options
@@ -43,6 +77,16 @@ while [[ $# -ge 1 ]]; do
       iso="$1"
       shift
       ;;
+    --biosks)
+      biosks="$1"
+      singleKickstart=false
+      shift
+      ;;
+    --efiks)
+      efiks="$1"
+      singleKickstart=false
+      shift
+      ;;
     --ks)
       ks="$1"
       shift
@@ -55,21 +99,6 @@ while [[ $# -ge 1 ]]; do
     ;;
   esac
 done
-
-if [ -z "$iso" ]; then
-  _error "Missing path to .iso file."
-  help
-fi
-
-if [[ -z "$device" ]]; then
-  _error "Missing device."
-  help
-fi
-
-if [[ -z "$ks" ]]; then
-  _error "Missing path to kickstart file."
-  help
-fi
 
 # required cmd line tools
 _check_tools "readlink basename syslinux mkfs.vfat partprobe"
@@ -136,11 +165,17 @@ prepare_boot() {
   ## BIOS-Boot
   execute "cp $iso_mnt/isolinux/* $device_mnt/"
   execute "mv \"$device_mnt/isolinux.cfg\" \"$device_mnt/syslinux.cfg\""
-  execute "sed -i '0,/.*append.*/s//\ \ append\ biosdevname=0\ net.ifnames=0\ initrd=initrd.img\ method=hd:LABEL=DATA:\/\ ks=hd:LABEL=BOOT:\/ks.cfg/' \"$device_mnt/syslinux.cfg\""
+  execute "sed -i '0,/.*append.*/s//\ \ append\ biosdevname=0\ net.ifnames=0\ initrd=initrd.img\ method=hd:LABEL=DATA:\/\ ks=hd:LABEL=BOOT:\/biosks.cfg/' \"$device_mnt/syslinux.cfg\""
   execute "sed -i 's/^TIMEOUT.*/timeout\ 100/i' \"$device_mnt/syslinux.cfg\""
   execute "sed -i 's/menu\ default//i' \"$device_mnt/syslinux.cfg\""
   execute "sed -i '/label\ linux/a \ \ menu\ default' \"$device_mnt/syslinux.cfg\""
-  execute "cp \"$ks\" \"$device_mnt/ks.cfg\""
+  if $singleKickstart; then
+    execute "cp \"$ks\" \"$device_mnt/biosks.cfg\""
+    execute "cp \"$ks\" \"$device_mnt/efiks.cfg\""
+  else
+    execute "cp \"$biosks\" \"$device_mnt/biosks.cfg\""
+    execute "cp \"$efiks\" \"$device_mnt/efiks.cfg\""
+  fi
   # overwrite .c32
   local syslinuxDir=$(dirname "$mbr_bin_path")
   execute "cp -f \"$syslinuxDir/../modules/bios/ldlinux.c32\" $device_mnt/"
@@ -153,7 +188,7 @@ prepare_boot() {
   execute "cp -rf $iso_mnt/images $device_mnt/"
   execute "sed -i 's/set default=\"1\"/set default=\"0\"/g' \"$device_mnt/EFI/BOOT/grub.cfg\""
   execute "sed -i 's/set timeout=60/set timeout=5/g' \"$device_mnt/EFI/BOOT/grub.cfg\""
-  execute "sed -i 's/inst.stage2=hd:LABEL=CentOS\\\x207\\\x20x86_64 quiet/biosdevname=0 net.ifnames=0 initrd=initrd.img method=hd:LABEL=DATA:\/ ks=hd:LABEL=BOOT:\/ks.cfg/g' \"$device_mnt/EFI/BOOT/grub.cfg\""
+  execute "sed -i 's/inst.stage2=hd:LABEL=CentOS\\\x207\\\x20x86_64 quiet/biosdevname=0 net.ifnames=0 initrd=initrd.img method=hd:LABEL=DATA:\/ ks=hd:LABEL=BOOT:\/efiks.cfg/g' \"$device_mnt/EFI/BOOT/grub.cfg\""
 }
 
 prepare_data() {
